######################################################################
# Automatically generated by qmake (3.0) Tue Mar 13 17:39:39 2018
######################################################################

TEMPLATE = app
TARGET = graduation_project
INCLUDEPATH += .

QT += widgets


# Input
HEADERS += button.h open_window.h sort_window.h widget.h
SOURCES += button.cpp main.cpp open_window.cpp sort_window.cpp widget.cpp
